version: '3'
services:
  blog:
    image: nginx:latest
    container_name: blog
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /home/ubuntu/Projects/Blog/docker/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/Projects/Blog/public:/usr/share/nginx/html
